---


- name: Elastic public signing key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Install apt-transport-https
  apt: 
    name: apt-transport-https 
    state: present

- name: Add Elastic repo
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Install Logstash
  apt: 
    name: logstash
    state: present
    force: true
    update_cache: yes

- name: Copy conf file
  template: 
    src: logstash.j2
    dest: /etc/logstash/conf.d/logstash.conf

- name: enable logstash
  systemd: 
    name: logstash.service
    enabled: yes

- name: start
  systemd: 
    name: logstash.service
    state: restarted
    
